#!/usr/bin/perl
#
# convert critical curve data generated by glafit to ds9 contour files
#
# usage: > crit_dat2con_wcs.pl out_crit.dat RA Dec 
#

if(($#ARGV+1)!=3){
 die "usage:\n > crit_dat2con_wcs.pl out_crit.dat RA0 DEC0\n";
}

open(IN,"$ARGV[0]") || die "File Not Found\n";

$f1="ds9crit_".$ARGV[0];
$f2="ds9caus_".$ARGV[0];

$ra0=$ARGV[1];
$dec0=$ARGV[2];
$cdec=cos((3.141592/180.0)*$dec0);

$f1 =~ s/.dat/.con/g;
$f2 =~ s/.dat/.con/g;

open(OUT1,">$f1") || die "Failed at Open\n";
open(OUT2,">$f2") || die "Failed at Open\n";

while(<IN>){
    @data=split;
    $xx=$data[0]*(-1.0)/(3600.0*$cdec)+$ra0;
    $yy=$data[1]/(3600.0)+$dec0;
    print OUT1 "$xx $yy\n";
    $xx=$data[4]*(-1.0)/(3600.0*$cdec)+$ra0;
    $yy=$data[5]/(3600.0)+$dec0;
    print OUT1 "$xx $yy\n\n";
    $xx=$data[2]*(-1.0)/(3600.0*$cdec)+$ra0;
    $yy=$data[3]/(3600.0)+$dec0;
    print OUT2 "$xx $yy\n";
    $xx=$data[6]*(-1.0)/(3600.0*$cdec)+$ra0;
    $yy=$data[7]/(3600.0)+$dec0;
    print OUT2 "$xx $yy\n\n";
}

close(IN);
close(OUT1);
close(OUT2);
